### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Kubuxu** [davidlazar/go-crypto#1]
Hi, I would love to use this package in the [IPFS](https://ipfs.io/) project but it unfortunately contains no license.

Would it be possible to release this package under MIT license so it can be used freely in other software?

**Comment by davidlazar** [comment]
I added a license (MIT).  Which packages are you looking to use in IPFS?

**Comment by Kubuxu** [comment]
I want to use streaming salsa20 for pre-shared key based private networks. One PSK defines the network, random nonce exchange on the connection initiation and the salsa20 stream encrypts whole communication.

We would run our regular channel over it so we are not worried about authentication of the encrypted stream.

Thank you.
